using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FleetManagement.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddDocument : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DROP TABLE IF EXISTS fleet.document CASCADE;
                CREATE TABLE fleet.document (
                    document_id integer GENERATED BY DEFAULT AS IDENTITY,
                    entity_type text NOT NULL,
                    entity_id integer NOT NULL,
                    category text,
                    file_name text NOT NULL,
                    content_type text NOT NULL,
                    file_path text NOT NULL,
                    file_size bigint NOT NULL,
                    uploaded_by integer NOT NULL,
                    uploaded_at timestamp with time zone NOT NULL,
                    notes text,
                    CONSTRAINT ""PK_document"" PRIMARY KEY (document_id)
                );
                CREATE INDEX ix_document_entity_type_entity_id
                    ON fleet.document (entity_type, entity_id);
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "document",
                schema: "fleet");
        }
    }
}
