services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.17.0
    user: root
    entrypoint: >
      bash -c "chmod go-w /usr/share/filebeat/filebeat.yml && filebeat run -e"
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - C:/Users/Josip/Source/Repos/FleetManagement/FleetManagement.API/logs:/var/log/fleet:ro
    depends_on:
      - elasticsearch

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin
    ports:
      - "5341:80"
    volumes:
      - seq-data:/data

volumes:
  es-data:
  seq-data: