server {
    listen 80;
    server_name _;

    location = / {
        return 302 /hr/;
    }

    location /en/ {
        alias /usr/share/nginx/html/en/;
        try_files $uri $uri/ /en/index.html;
    }

    location /hr/ {
        alias /usr/share/nginx/html/hr/;
        try_files $uri $uri/ /hr/index.html;
    }
}
